# Generated by Django 2.0.4 on 2018-04-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.IntegerField()),
                ('videos_vost', models.TextField(null=True)),
                ('videos_manual', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='serie',
            name='anime_id',
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='timer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.AddField(
            model_name='episode',
            name='anime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Anime'),
        ),
    ]
