# Generated by Django 2.0.4 on 2018-04-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_auto_20180411_0110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime_id', 'episode_id')},
        ),
    ]
