# Generated by Django 2.0.4 on 2018-04-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_auto_20180411_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='slug',
        ),
    ]
