# Generated by Django 2.0.4 on 2018-04-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_auto_20180411_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Studio'),
        ),
    ]
