# Generated by Django 2.0.4 on 2018-04-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20180411_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genres',
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='anime.Genre'),
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studios',
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(to='anime.Studio'),
        ),
    ]
