# Generated by Django 2.0.4 on 2018-04-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_anime_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.CharField(max_length=500),
        ),
    ]
