# Generated by Django 2.0.4 on 2018-04-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_auto_20180411_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(upload_to=''),
        ),
    ]
