# Generated by Django 2.0.4 on 2018-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_auto_20180411_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(upload_to='static/posters'),
        ),
    ]
